### ISSUE TITLE
crashed in  __lws_close_free_wsi  while doing KVS streaming

### ISSUE THREAD

**Issue by liutuzhao** [awslabs/amazon-kinesis-video-streams-pic#96]
**Logging**
[crash-in-lws-malloc_state.zip](https://github.com/awslabs/amazon-kinesis-video-streams-pic/files/5650029/crash-in-lws-malloc_state.zip)

**Describe the bug**
We using this sdk in our arm camera to do KVS streaming, and catch one crash while doing upload of video frame uploading.
We checked the core dump , and found the following stack:
09:01:05  (gdb) where
#0  0x0081da00 in __malloc_state ()
#1  0x0032d5d8 in __lws_close_free_wsi ()
#2  0x0032d5d8 in __lws_close_free_wsi ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**SDK version number**
1.4.0

**Open source building**
default open source version confiuration in this sdk.

**To Reproduce**
Check the log ,  camera is doing kvs streaming all the time.
And network seem poor.

**Comment by MushMal** [comment]
@liutuzhao there is almost no information to go with. Here is what I see

* You have a custom application that we have no clue about.
* Your application seems to be doing both KVS streaming and WebRTC.
* There are pieces of your application that seem to detect a hung and something terminates your application?
* You seem to have a corrupt crash stack that points to malloc. The top of the stack is missing so I am not sure I can tell what code path leads to it. These types of crash stacks could happen on OOM or whenever there is a memory corruption due to an buffer override. Potentially, a malloc earlier that failed but the application dereferences a bad allocation pointer?

We can't debug your application. See if you can do some debugging your self to narrow down the scenario to get to the bottom of this issue. Try to run stock sample with debug symbols.

As there is no indication of KVS SDK cause, I am removing the 'bug' tag.

**Comment by disa6302** [comment]
Closing because of an equivalent ticket open in webrtc. (https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/993)
